#' Design file for cynomolgus macaques infected with M. tuberculosis
#' 
#' A dataset containing sample information such as time point and clinical status.
#' 
#' @format A data frame with 436 rows and 7 variables.
#' \describe{
#'   \item{columnname}{names matching column names in expression dataset}
#'   \item{monkey_id}{id assigned to annotate each monkey}
#'   \item{timepoint}{times at which samples were drawn, in days}
#'   \item{timerange}{groups time points into stages}
#'   \item{sample_id}{id assigned to annotate each sample}
#'   \item{clinical_status}{denotes if disease is active or latent}
#' }
#' @source \url{http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE84152}
"tb.design"


#' Microarray dataset on cynomolgus macaques infected with M. tuberculosis
#' 
#' A dataset containing gene expression data on 38 monkeys at various time 
#' points.
#' 
#' @format A data frame with 1000 rows and 436 columns, where each row is a 
#' probe and each column a sample.
#' 
#' @source \url{http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE84152}
"tb.expr"


#' Flow dataset on cynomolgus macaques infected with M. tuberculosis
#' 
#' A dataset containing flow absolute count and percentage data
#' 
#' @format A data frame with 194 rows of samples and 13 flow variables.
#' 
#' @source \url{http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE84152}
"tb.flow"


#' Baylor Modules
#' 
#' A list containing the baylor modules (gene sets)
#' 
#' @format A large list containing 260 gene sets.
#' 
#' @source baylor modules
"modules"


#' Module Activity Scores
#' 
#' This is a dataset containing module activity scores for cynomolgus macaques 
#' infected with M. tuberculosis. For a given module, monkey, and time point, 
#' each score was calculated by summing the difference in probe-level 
#' post-infection expression values and the average basline expression value for
#' all probes within the module. This sum was then divided by the number of 
#' probes within each module plus the number of samples within each time point.
#' 
#' @format A data frame with 194 rows of samples and 260 columns of modules.
#'   
#' @source baylor modules and
#'   \url{http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE84152}
"module.as"


#' Gene Symbols
#' 
#' A vector of gene symbols to match the probes ids in expression
#' 
#' @format A vector of 1000 gene symbols
#' 
#' @source Illumina
"gene.symbols"


#' Design information object
#' 
#' A list generated by \code{\link{desInfo}}. Contains matched design and
#' expression datasets, along with defined design parameters.
#' 
#' @format A list of length 16. See \code{\link{desInfo}} for details.
#'   
#' @source \code{\link{desInfo}}
"des.info"


#' Model results object 
#' 
#' A list generated by \code{\link{genModelResults}}.
#' 
#' @format A list of length 3. See \code{\link{genModelResults}} for details.
#' 
#' @source \code{\link{genModelResults}}
"model.results"


